# Generated by Django 3.2.9 on 2021-11-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211114_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses_taken',
            field=models.TextField(),
        ),
    ]
