# Generated by Django 3.2.9 on 2021-11-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_user_courses_taken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='myuser',
        ),
    ]
