# Generated by Django 3.2.9 on 2021-11-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_user_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='registered_course',
            field=models.TextField(null=True),
        ),
    ]
