# Generated by Django 3.2.9 on 2021-11-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211127_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='courses_taken',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='registered_courses',
        ),
    ]
