# Generated by Django 3.2.9 on 2021-11-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_courses', '0002_auto_20211114_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='seats_available',
            field=models.IntegerField(default=0),
        ),
    ]
