# Generated by Django 3.2.9 on 2021-11-14 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pick_courses', '0003_alter_course_seats_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prof_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prof_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='seats_available',
        ),
        migrations.CreateModel(
            name='available_course',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pick_courses.course')),
                ('prof_name', models.CharField(max_length=100)),
                ('prof_id', models.CharField(max_length=100)),
                ('seats_available', models.IntegerField(default=0)),
                ('description', models.TextField()),
            ],
            bases=('pick_courses.course',),
        ),
    ]
