# Generated by Django 3.2.9 on 2021-11-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_courses', '0004_auto_20211114_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_course',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
