# Generated by Django 3.2.9 on 2021-11-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_courses', '0005_alter_available_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_course',
            name='prerequisites',
            field=models.TextField(null=True),
        ),
    ]
