# Generated by Django 3.2.9 on 2021-11-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_courses', '0006_available_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_course',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='available_course',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
