# Generated by Django 3.2.9 on 2021-11-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_courses', '0007_auto_20211121_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_course',
            name='days',
            field=models.TextField(null=True),
        ),
    ]
