# Generated by Django 3.2.9 on 2021-11-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pick_courses', '0010_course_prerequsitecourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available_course',
            name='prerequisites',
        ),
    ]
